/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package personalwebsitetesting;
import java.lang.System;
import java.lang.String;


public class PersonalWebsiteTesting {

    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "/Applications/chromedriver_mac64/chromedriver");

    }
}
